### PR TITLE
Blog post on various ways to add mobility to Unet Sim 

### PR DESCRIPTION
**Pull request by notthetup**

### CODE REVIEW

**Comment by manuignatius** [comment]
Image was not getting rendered in the preview. Otherwise, no comments.

**Review by manuignatius — APPROVED** [review]

**Comment by notthetup** [comment]
@manuignatius What do you mean by preview? The landing page?

Screen Shot 2021-05-20 at 15 45 34

**Comment by manuignatius** [comment]
https://github.com/org-arl/unet-blog/blob/mobility/_posts/2021-04-27-motion-models.md

**Comment by notthetup** [comment]
Ah! OK That shouldn't work actually. The image location wrt to the post page is different in GitHub vs the rendered output. So even using relative references they won't render on the GitHub preview.

The only reason https://github.com/org-arl/unet-blog/blob/mobility/_posts/2020-07-06-whats-so-super-about-super-tdma.md works is browsers autocorrect `http://blog.unetstack.net/../assets/....` to `http://blog.unetstack.net/assets/....`

**Comment by notthetup** [comment]
See the generated HTML is `https://blog.unetstack.net/../assets/img/stdma/stdma-lpd.png` but the network request  is done on `https://blog.unetstack.net/assets/img/stdma/stdma-lpd.png`
Screen Shot 2021-05-20 at 16 09 50

**Review by mchitre — APPROVED** [review]
Nice!

**Pull request merged**
