### PR TITLE
Table of contents

### PR DESCRIPTION
**Pull request by jjophi**
Added a view for listing links to all blogs. This view is  available in home page and individual blog pages. Please see the screens:

Screenshot 2024-08-05 at 8 23 19 PM
Screenshot 2024-08-05 at 8 23 30 PM

### CODE REVIEW

**Review by manuignatius — APPROVED** [review]

**Comment by manuignatius** [comment]
For @mchitre @notthetup 's context, I had requested this feature here: https://github.com/org-arl/unet-blog/issues/70

**Review by mchitre — APPROVED** [review]
Not really in a position to technically review. @manuignatius and @notthetup's reviews should be sufficient.

**Comment by manuignatius** [comment]
> Not really in a position to technically review. @manuignatius and @notthetup's reviews should be sufficient.

  Mostly for the overall OK that I requested your review :)

**Comment by notthetup** [comment]
What's the mechanism for opening this list?

**Comment by jjophi** [comment]
> What's the mechanism for opening this list?

You can click on the Table of contents button:

image

**Comment by notthetup** [comment]
The placement of that button doesn't go with the rest of the design no?

Does it make sense to just have a separate "page" called `/all` which we can then link from the top menubar instead of doing this overlay?

**Comment by manuignatius** [comment]
Decided to go with @notthetup 's suggestion during today's (8 August 2024) meeting.

**Comment by jjophi** [comment]
Updated the blog listing UI as discussed today (8 August 2024). Main changes are:
- 'Blog List' link added along with the main links
- separate page for blog listing (removed overlay)

 Please see the UI:

image

**Comment by manuignatius** [comment]
@notthetup for your review and approval

**Review by notthetup — APPROVED** [review]

**Pull request merged**
